release:
  github:
    owner: rusq
    name: osx-callhistory-decryptor
  draft: false
  prerelease: auto
  mode: append
  header: |
    Welcome to the new release of {{ .ProjectName }}!
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: ./README.md
    - glob: ./LICENSE
builds:
  -
    ldflags:
    - -s -w -X main.version={{.Version}}
    goarch:
      - amd64
      - "386"
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    ignore:
      - goos: darwin
        goarch: "386"
